CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: '/cluster/scratch/oilter/output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 10

DATASET:
  DATASET: kitti
  ROOT: /cluster/scratch/oilter/data/
  TEST_SET: 'list/kitti/train.lst'
  TRAIN_SET: 'list/kitti/train.lst'
  NUM_CLASSES: 19
MODEL:
  NAME: pidnet_large
  NUM_OUTPUTS: 2
  PRETRAINED: "/cluster/home/oilter/PIDNet/pretrained_models/cityscapes/PIDNet_L_Cityscapes_test.pt"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 1224
  - 370
  BASE_SIZE: 1224
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 484
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 1224
  - 370
  BASE_SIZE: 1224
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
